server:
  port: 3000

app:
  jwtSecret: secretKey
  jwtExpirationMs: 1800000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost


spring:
  application:
    name: authentication-service
  datasource:
    url: jdbc:h2:mem:usersDb
    platform: h2
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
